title: Greg Surma - Portfolio
author: Greg Surma
email: grzegorz.surma@icloud.com
description: Greg Surma - iOS, AI, Machine Learning, Swit, Python, Objective-C
url: "https://gsurma.github.io"
twitter_username: gsurma
github_username:  gsurma
google_analytics: UA-110543961-1

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap