title: Hedelong Shi - Portfolio
author: Hedelong Shi
email: shihedelong@gmail.com
description: Hedelong Shi - Android, AI, Machine Learning, Python, Kotlin
url: "https://shihedelong.github.io"
twitter_username: Neo Shihe
github_username:  shihedelong
google_analytics: UA-110543961-1

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
